# Nginx Deployment with ConfigMap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          volumeMounts:
            - mountPath: "/etc/nginx/nginx.conf"
              subPath: nginx.conf
              name: nginx-config-volume
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config


  